apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: go-web-server
  newName: emunari/go-web-server
  newTag: e82b6b2ff445cfeaa37d11d52a91aa874571fba6
