name: CD Workflow

on:
  push:
    branches: [appset-helm-deps]

jobs:
  build:
    name: Build and Push GO Web Server Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      # with:
      #   ref: ${{ github.ref }}
      #   repository: dumunari/go-web-server
      #   github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWD}}
        repository: ${{secrets.DOCKERHUB_USER}}/go-web-server
        tags: ${{github.sha}}, latest